universe = vanilla
transfer_input_files = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/w.dat,/nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/y.dat
executable = /home/michael.wright/bin/pointlens
arguments = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/w.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/y.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/fReal.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/data/fImag.dat 512 0 
log = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/file_generators_lensed_testing/data/lens_generation.log
output = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/file_generators_lensed_testing/data/lens_generation.out
error = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/file_generators_testing/file_generators_lensed_testing/data/lens_generation.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
request_cpus = 8
request_memory = 16 GB 
accounting_group = file.generators.testing.tag
queue 1
