universe = vanilla
transfer_input_files = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/w.dat,/nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/y.dat
executable = /home/michael.wright/bin/sislens
arguments = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/w.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/y.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/fReal.dat /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/fImag.dat 1500 800 0 
log = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/lens_generation.log
output = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/lens_generation.out
error = /nfshome/store01/users/michael.wright/Gravelamps/review_materials/lens_generation_testing/sislens-geo/data/lens_generation.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
request_cpus = 16
request_memory = 16 GB 
accounting_group = aluk.dev.o4.cbc.gwlensing
queue 1
